"""
Communication device class
"""

import io
import libscrc
import serial
from helper import decode_msg


class GenericCommsDevice():
    """
    Base communication device that serializes and deserializes messages
    """

    def __init__(self, port: str, baudrate: int):
        self.current_msg = io.BytesIO()
        self.length = -1
        self.ser = serial.Serial(
            port=port, baudrate=baudrate, bytesize=8, timeout=2, stopbits=serial.STOPBITS_ONE
        )

    @staticmethod
    def __get_crc32(b_in: bytes) -> int:
        """
        """
        return libscrc.crc32(b_in)

    def transmit(self, msg) -> None:
        """
        Expects a TelemMessages object
        """
        buf = io.BytesIO()
        # Accessing LCM autogenerated method
        # pylint: disable=[protected-access]
        msg._encode_one(buf)
        # pylint: enable=[protected-access]
        crc32 = self.__get_crc32(buf.getbuffer().tobytes())
        msg.crc = crc32.to_bytes(4, 'big')
        buf = io.BytesIO()
        # Accessing LCM autogenerated method
        # pylint: disable=[protected-access]
        msg._encode_one(buf)
        # pylint: enable=[protected-access]
        self.ser.write(buf.getbuffer().tobytes())

    def receive(self):
        """
        Receives a single message and returns a tuple of (bool, TelemMessages object)
        Blocking call
        """
        while self.ser.inWaiting():
            read_byte = self.ser.read()[0]
            self.current_msg.write(read_byte.to_bytes(1, 'big'))

            if read_byte == 0x7e:
                # start of new message
                length_bytes = self.ser.read(size=2)
                self.length = int.from_bytes(length_bytes, 'big')
                self.current_msg.write(length_bytes)
            else:
                if len(self.current_msg.getbuffer()) == self.length + 8:
                    # check crc
                    raw_data = self.current_msg.getbuffer().tobytes()
                    calc_crc32 = self.__get_crc32(raw_data[:-4])
                    msg_crc32 = int.from_bytes(raw_data[-4:], 'big')
                    if msg_crc32 == calc_crc32:
                        if raw_data[3] == 5:
                            self.current_msg.seek(0)
                            out = decode_msg(self.current_msg)
                            self.length = -1
                            self.current_msg = io.BytesIO()
                            return True, out

        return False, None
