"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import TelemMessages.Header

import TelemMessages.PIDController

class GroundStationPIDSetResponse(object):
    __slots__ = ["header", "controller_number", "controller", "crc"]

    __typenames__ = ["TelemMessages.Header", "byte", "TelemMessages.PIDController", "byte"]

    __dimensions__ = [None, None, None, [4]]

    def __init__(self):
        self.header = TelemMessages.Header()
        self.header.flag = 0x7e
        self.header.type = 0x8
        self.header.length = bytes([ 0x0, 0x91 ])
        self.controller_number = 0
        self.controller = TelemMessages.PIDController()
        self.crc = b""

    def encode(self):
        buf = BytesIO()
        buf.write(GroundStationPIDSetResponse._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == TelemMessages.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        buf.write(struct.pack(">B", self.controller_number))
        assert self.controller._get_packed_fingerprint() == TelemMessages.PIDController._get_packed_fingerprint()
        self.controller._encode_one(buf)
        buf.write(bytearray(self.crc[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != GroundStationPIDSetResponse._get_packed_fingerprint():
            raise ValueError("Decode error")
        return GroundStationPIDSetResponse._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = GroundStationPIDSetResponse()
        self.header = TelemMessages.Header._decode_one(buf)
        self.controller_number = struct.unpack(">B", buf.read(1))[0]
        self.controller = TelemMessages.PIDController._decode_one(buf)
        self.crc = buf.read(4)
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if GroundStationPIDSetResponse in parents: return 0
        newparents = parents + [GroundStationPIDSetResponse]
        tmphash = (0x4333eafa5f1ff412+ TelemMessages.Header._get_hash_recursive(newparents)+ TelemMessages.PIDController._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if GroundStationPIDSetResponse._packed_fingerprint is None:
            GroundStationPIDSetResponse._packed_fingerprint = struct.pack(">Q", GroundStationPIDSetResponse._get_hash_recursive([]))
        return GroundStationPIDSetResponse._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", GroundStationPIDSetResponse._get_packed_fingerprint())[0]

