"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

from .. import TelemMessages



class GroundStationWaypoints(object):
    __slots__ = ["header", "num_waypoints", "waypoints"]

    __typenames__ = ["TelemMessages.Header", "byte", "TelemMessages.Waypoint"]

    __dimensions__ = [None, None, [5]]

    def __init__(self):
        self.header = TelemMessages.Header()
        self.header.flag = 0x7e
        self.header.type = 0x4
        self.header.length = bytes([ 0x0, 0x7e ])
        self.num_waypoints = 0
        self.waypoints = [ TelemMessages.Waypoint() for dim0 in range(5) ]

    def encode(self):
        buf = BytesIO()
        buf.write(GroundStationWaypoints._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == TelemMessages.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        buf.write(struct.pack(">B", self.num_waypoints))
        for i0 in range(5):
            assert self.waypoints[i0]._get_packed_fingerprint() == TelemMessages.Waypoint._get_packed_fingerprint()
            self.waypoints[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != GroundStationWaypoints._get_packed_fingerprint():
            raise ValueError("Decode error")
        return GroundStationWaypoints._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = GroundStationWaypoints()
        self.header = TelemMessages.Header._decode_one(buf)
        self.num_waypoints = struct.unpack(">B", buf.read(1))[0]
        self.waypoints = []
        for i0 in range(5):
            self.waypoints.append(TelemMessages.Waypoint._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if GroundStationWaypoints in parents: return 0
        newparents = parents + [GroundStationWaypoints]
        tmphash = (0x8b561a05e7cde396+ TelemMessages.Header._get_hash_recursive(newparents)+ TelemMessages.Waypoint._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if GroundStationWaypoints._packed_fingerprint is None:
            GroundStationWaypoints._packed_fingerprint = struct.pack(">Q", GroundStationWaypoints._get_hash_recursive([]))
        return GroundStationWaypoints._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", GroundStationWaypoints._get_packed_fingerprint())[0]

