"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class Header(object):
    __slots__ = ["flag", "length", "type"]

    __typenames__ = ["byte", "byte", "byte"]

    __dimensions__ = [None, [2], None]

    def __init__(self):
        self.flag = 0
        self.length = b""
        self.type = 0

    def encode(self):
        buf = BytesIO()
        buf.write(Header._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">B", self.flag))
        buf.write(bytearray(self.length[:2]))
        buf.write(struct.pack(">B", self.type))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Header._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Header._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Header()
        self.flag = struct.unpack(">B", buf.read(1))[0]
        self.length = buf.read(2)
        self.type = struct.unpack(">B", buf.read(1))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if Header in parents: return 0
        tmphash = (0x23b4b6904caa43c8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Header._packed_fingerprint is None:
            Header._packed_fingerprint = struct.pack(">Q", Header._get_hash_recursive([]))
        return Header._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Header._get_packed_fingerprint())[0]

