"""
Generates the helper.py file
"""

import json
import os
import sys


def search_in_file(phrase: str, lines: list) -> int:
    """
    Searches for string in each line
    """
    for (i, line) in enumerate(lines):
        if phrase in line:
            return i
    return -1


def replace_import(directory: str):
    file_names = [f for f in directory if (str(f))[-3:] == ".py"]
    for file_name in file_names:
        with open(py_path + file_name, "r+") as fd:
            contents = fd.readlines()
            print("Opened " + file_name)

            # Get locations
            import_index = search_in_file("import TelemMessages.", contents)
            class_index = search_in_file("class", contents)
            if import_index == -1 or class_index == -1 or class_index < import_index:
                print("import and/or class not found, skip")
                continue

            # Replace import
            contents[import_index] = "from .. import TelemMessages\n"
            # Replace with empty lines
            for i in range(import_index + 1, class_index):
                contents[i] = "\n"

            fd.seek(0)
            fd.writelines(contents)


if __name__ == "__main__":
    loc = os.path.realpath(os.path.dirname(__file__))

    msg_path = loc + '/../TelemMessages/'
    py_path = loc + '/../py/TelemMessages/'

    # Import replacement required for submodule support
    print("Import replacement")
    replace_import(os.listdir(py_path))

    helper = "\"\"\"\n"
    helper += "Autogenerated decoder\n"
    helper += "\"\"\"\n"
    helper += "\n"
    helper += "from . import TelemMessages\n"
    helper += "\n"
    helper += "\n"
    helper += "def decode_msg(buf):\n"
    helper += "    \"\"\"\n"
    helper += "    Returns message class based on header type\n"
    helper += "    \"\"\"\n"
    helper += "\n"
    helper += "    raw_data = buf.getbuffer().tobytes()\n"
    # Spaces before if
    helper += "    "

    # Open JSON file containing metadata
    with open(msg_path + "messages.json") as json_file:
        data = json.load(json_file)
        for msg in data:
            length = msg["length"].to_bytes(2, byteorder="big")

            # Open each message class
            with open(py_path + msg["name"] + ".py", "r+") as fd:
                contents = fd.readlines()
                print("opened " + msg["name"])

                # Insert helper methods for message identification
                index = search_in_file("self.header", contents)
                if index == -1:
                    print("self.header not found in file!")
                    sys.exit(-1)

                print(index)
                contents.insert(index + 1, "        self.header.flag = 0x7e\n")
                contents.insert(index + 2, "        self.header.type = " + hex(msg["type"]) + "\n")
                contents.insert(index + 3, "        self.header.length = bytes([ " + hex(length[0]) + ", " + hex(length[1]) + " ])\n")

                fd.seek(0)
                fd.writelines(contents)

                # if or elif with spaces
                helper += "if raw_data[3] == " + hex(msg["type"]) + ":\n"
                helper += "        return TelemMessages." + msg["name"] + "()._decode_one(buf)\n"
                helper += "    el"

    helper += "se:\n"
    helper += "        return None\n"
    output_file = open(py_path + "../helper.py", "w")

    output_file.write(helper)
    output_file.close()
